[package]
name = "nccl"
version = "0.0.1"
authors = ["Peter Jin <peterhaijin@gmail.com>"]
build = "build.rs"

[lib]
name = "nccl"
path = "src/lib.rs"

[build-dependencies]
gcc = "*"

[dependencies]
cuda = { path = "../libcuda" }
libc = "*"
