[package]
name = "nccl_sys"
version = "0.0.1"
authors = ["Peter Jin <peterhaijin@gmail.com>"]
build = "build.rs"

[lib]
name = "nccl_sys"
path = "ffi.rs"

[build-dependencies]
gcc = "*"

[dependencies]
cuda = { git = "https://github.com/peterhj/libcuda.git" }
libc = "*"
